# Generated by Django 3.2.3 on 2021-06-24 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipog', models.CharField(max_length=200, unique=True)),
                ('usuarioid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoIng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoing', models.CharField(max_length=200, unique=True)),
                ('usuarioId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField(max_length=12)),
                ('usuarioId', models.IntegerField()),
                ('tipoing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFinanzas.tipoing')),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField(max_length=12)),
                ('usuarioId', models.IntegerField()),
                ('tipog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFinanzas.tipog')),
            ],
        ),
    ]
