# Generated by Django 3.2.3 on 2021-06-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='usuarioId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='usuarioId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tipog',
            name='usuarioid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tipoing',
            name='usuarioId',
            field=models.IntegerField(null=True),
        ),
    ]
